### ISSUE TITLE
Can't get PS3 dualshock controller working over USB/Bluetooth

### ISSUE THREAD

**Issue by tolgap** [raelgc/ubuntu_xboxdrv#11]
Hi Rael,

I've been having `xboxdrv` issues since I upgraded to 14.04. Once I start xboxdrv, I see the player 1 LED turn red on my DS3 controller, but after 3 seconds, all 4 player LEDs start blinking again.

My PC does not recognize the controller either, I use `jstest-gtk` to test it. It used to work on 13.04.

This is what happens when I do a fresh `xboxdrv` install:
- I do `sudo rm -f /dev/input/js*` to clear joystick inputs
- I plug in my DS3 controller
- I see all 4 LEDs blinking
- Restart the service with `sudo service xboxdrv restart`
- Notice player 1 LED is full red
- After 3 seconds it "loses" connection and the 4 player LEDs are blinking again
- In `ls /dev/input/js*` I see 4 joystick inputs `js1 js2 js3 js4`

If you need any more debug info, please let me know!

**Comment by mysticjoker** [comment]
This just a little different. I have keyboard and mouse and trying to get my ps3 controller working. Done it in past plenty of times. But I notice back then I had my keyboard and mouse were usb. Now I have both bluetooth. Is their a way to get Ubuntu to recognize my controller by USB?
