### ISSUE TITLE
Bad Lexical Cast?

### ISSUE THREAD

**Issue by ZeeCrazyAtheist** [raelgc/ubuntu_xboxdrv#29]
bad lexical cast: source type value could not be interpreted as target

What is this and how do I fix it :frowning:

**Comment by ZeeCrazyAtheist** [comment]
root@e-code:/home/ken/.xbox-configs/configs# cat *.xboxdrv
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear = true
trigger-as-button = true
silent = true
force-feedback = true 

[ui-axismap]
x1=KEY_A:KEY_D
y1=KEY_W:KEY_S
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_LEFTSHIFT
x = KEY_D
y = KEY_C
lt = BTN_RIGHT
rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_ESC
back  = KEY_ESC
# guide = KEY_ESC
 

# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true
 
[ui-axismap]
x1=KEY_A:KEY_D
y1=KEY_W:KEY_S
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_LEFTSHIFT
x = KEY_D
y = KEY_C
lt = BTN_RIGHT
rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_I
back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
# Mouse Emulation
# ===============
#
# This configuration file emulates a mouse. The left stick controls
# the cursor, the right stick becomes a horizontal and vertical scroll
# wheel, the dpad acts as cursor keys, the start and back buttons
# become forward and back buttons, the guide button escape and LB and
# RB become page up and page down and the face button act as mouse
# button.

[xboxdrv]
ui-clear=true


[ui-axismap]
x1^dead:4000 = REL_X:750:-1
y1^dead:4000 = REL_Y:750:-1

# y2^dead:6000^invert = REL_WHEEL:5:100
# x2^dead:6000 = REL_HWHEEL:5:100
# trigger^invert=REL_WHEEL:5:100

y2^dead:6000^invert = rel-repeat:REL_WHEEL:1:50
x2^dead:6000 = rel-repeat:REL_HWHEEL:1:50
# trigger^invert = rel-repeat:REL_WHEEL:1:50

lt = KEY_VOLUMEDOWN:20
rt = KEY_VOLUMEUP:20

[ui-buttonmap]
a = BTN_LEFT
b = BTN_RIGHT
x = BTN_MIDDLE
y = KEY_ENTER

rb = KEY_PAGEDOWN
lb = KEY_PAGEUP

tl = KEY_ESC 
tr = KEY_ENTER

[ui-buttonmap]
dl = KEY_LEFT
dr = KEY_RIGHT
du = KEY_UP
dd = KEY_DOWN

lt = KEY_VOLUMEDOWN 
rt = KEY_VOLUMEUP

[ui-buttonmap]
start = KEY_FORWARD
back  = KEY_BACK
#guide = 

# EOF #
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true

[ui-axismap]
x1=KEY_A:KEY_D
y1=KEY_W:KEY_S
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_SPACE
x = KEY_TAB
y = KEY_TAB
lt = BTN_LEFT
rt = BTN_LEFT
 
rb = KEY_RIGHT
lb = KEY_LEFT
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_ESC
back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true
 
[ui-axismap]
x1=KEY_LEFT:KEY_RIGHT
y1=KEY_UP:KEY_DOWN
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
#b = KEY_LEFTSHIFT
#x = KEY_D
#y = KEY_C
lt = BTN_RIGHT
rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_I
back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true

[ui-axismap]
x1=KEY_LEFT:KEY_RIGHT
#y1=KEY_W:KEY_S
#x2^dead:4000 = REL_X:750:-1
#y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_RIGHT
x = KEY_LEFT
y = KEY_ENTER
#lt = BTN_RIGHT
#rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
#du = rel:REL_WHEEL:-1:500
#dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_ESC
#back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #


This is the configs

**Comment by ZeeCrazyAtheist** [comment]
root@e-code:/home/ken/.xbox-configs/configs# cat *.xboxdrv
```
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear = true
trigger-as-button = true
silent = true
force-feedback = true 

[ui-axismap]
x1=KEY_A:KEY_D
y1=KEY_W:KEY_S
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_LEFTSHIFT
x = KEY_D
y = KEY_C
lt = BTN_RIGHT
rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_ESC
back  = KEY_ESC
# guide = KEY_ESC
 

# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true
 
[ui-axismap]
x1=KEY_A:KEY_D
y1=KEY_W:KEY_S
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_LEFTSHIFT
x = KEY_D
y = KEY_C
lt = BTN_RIGHT
rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_I
back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
# Mouse Emulation
# ===============
#
# This configuration file emulates a mouse. The left stick controls
# the cursor, the right stick becomes a horizontal and vertical scroll
# wheel, the dpad acts as cursor keys, the start and back buttons
# become forward and back buttons, the guide button escape and LB and
# RB become page up and page down and the face button act as mouse
# button.

[xboxdrv]
ui-clear=true


[ui-axismap]
x1^dead:4000 = REL_X:750:-1
y1^dead:4000 = REL_Y:750:-1

# y2^dead:6000^invert = REL_WHEEL:5:100
# x2^dead:6000 = REL_HWHEEL:5:100
# trigger^invert=REL_WHEEL:5:100

y2^dead:6000^invert = rel-repeat:REL_WHEEL:1:50
x2^dead:6000 = rel-repeat:REL_HWHEEL:1:50
# trigger^invert = rel-repeat:REL_WHEEL:1:50

lt = KEY_VOLUMEDOWN:20
rt = KEY_VOLUMEUP:20

[ui-buttonmap]
a = BTN_LEFT
b = BTN_RIGHT
x = BTN_MIDDLE
y = KEY_ENTER

rb = KEY_PAGEDOWN
lb = KEY_PAGEUP

tl = KEY_ESC 
tr = KEY_ENTER

[ui-buttonmap]
dl = KEY_LEFT
dr = KEY_RIGHT
du = KEY_UP
dd = KEY_DOWN

lt = KEY_VOLUMEDOWN 
rt = KEY_VOLUMEUP

[ui-buttonmap]
start = KEY_FORWARD
back  = KEY_BACK
#guide = 

# EOF #
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true

[ui-axismap]
x1=KEY_A:KEY_D
y1=KEY_W:KEY_S
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_SPACE
x = KEY_TAB
y = KEY_TAB
lt = BTN_LEFT
rt = BTN_LEFT
 
rb = KEY_RIGHT
lb = KEY_LEFT
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_ESC
back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true
 
[ui-axismap]
x1=KEY_LEFT:KEY_RIGHT
y1=KEY_UP:KEY_DOWN
x2^dead:4000 = REL_X:750:-1
y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
#b = KEY_LEFTSHIFT
#x = KEY_D
#y = KEY_C
lt = BTN_RIGHT
rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
du = rel:REL_WHEEL:-1:500
dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_I
back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
# Supports the default controls in the way I thought was logical. 
# 
# A is jump
# B is sneak
# X is drop
# Y is chat
# Scroll with the DPAD
# RT is left click
# LT is right click
# Left joystick is WASD
# Right joystick is Mouse
 
[xboxdrv]
ui-clear=true
trigger-as-button = true
silent = true

[ui-axismap]
x1=KEY_LEFT:KEY_RIGHT
#y1=KEY_W:KEY_S
#x2^dead:4000 = REL_X:750:-1
#y2^dead:4000 = REL_Y:750:-1
 
 
#trigger^invert = rel-repeat:REL_WHEEL:1:50
 
 
 
 
 
[ui-buttonmap]
a = KEY_SPACE
b = KEY_RIGHT
x = KEY_LEFT
y = KEY_ENTER
#lt = BTN_RIGHT
#rt = BTN_LEFT
 
# rb = KEY_PAGEDOWN
# lb = KEY_PAGEUP
 
# tl = KEY_BACKSPACE
# tr = KEY_SPACE
 
[ui-buttonmap]
# dl = KEY_LEFT
# dr = KEY_RIGHT
#du = rel:REL_WHEEL:-1:500
#dd = rel:REL_WHEEL:1:500
 
# lt = KEY_VOLUMEDOWN
# rt = KEY_VOLUMEUP
 
[ui-buttonmap]
start = KEY_ESC
#back  = KEY_ESC
# guide = KEY_ESC
 
# EOF #
```

**Comment by raelgc** [comment]
@ZeeCrazyAtheist If you try without this config file, it works fine?

**Comment by ZeeCrazyAtheist** [comment]
well this is 5 config files put together, The comments are the start of each file but yeah i'll try with out

**Comment by ZeeCrazyAtheist** [comment]
ok that works it, but it seemed like a little script I had for starting up a tmux session of the regular program wouldn't start

**Comment by ZeeCrazyAtheist** [comment]
Also, dunno how I'm supposed to add the configs back in now if its started

**Comment by raelgc** [comment]
You can edit `/etc/default/xboxdrv` and add options to `XBOXDRV_OPTIONS`.

**Comment by ZeeCrazyAtheist** [comment]
yes, removing them from the options is what fixed it :frowning:

**Comment by ZeeCrazyAtheist** [comment]
Ok I found out force-feedback doesn't like to be put in config files
