### ISSUE TITLE
Multiple controllers using match rules

### ISSUE THREAD

**Issue by gyates100895** [raelgc/ubuntu_xboxdrv#30]
I have a proposal I am willing to develop further if there is any desire(seriously, at all). Maybe modifying the default script to have a multiple controller matching rule trigger the likes of "trigger as button" followed by an editable code block for the rules. Right now im envisioning one for each controller slot. The init script would then parse this into something like CONTROLLER MATCHx and call each match block before the default PADOPTIONS block when the final command is executed. I believe this would allow the daemon service to discriminate between controllers and allow the ability to give different controllers their own set of config slots to switch with. I may be wrong but please comment with input. That's collaborative programming in a nutshell right? :D

**Comment by raelgc** [comment]
@gyates100895 Sounds good!

Please, create a pull-request with your modified script :)
