### ISSUE TITLE
Multiple connected controllers support

### ISSUE THREAD

**Issue by gyates100895** [raelgc/ubuntu_xboxdrv#32]
I plan on working in support for multiple controllers. I feel that there was some intention at this projects inception.The current idea is to call more instances with the same options for each. This is because my setup is this: ubuntu-xboxdrv collects the options, and calls xboxdrv. xboxdrv consists of four controller slots with their own match rules (i have rockband instruments connected along with a wired 360 controller). After the controllers options are added (eg chatpad), they are followed by a config file consisting of only button maps. 
my endgame is to have ubuntu xboxdrv dynamically create and manage the instances of xboxdrv depending on which controller slots are filled in. eg if only controller slot 0, create one instance. if 0 through 2 then create 3 instances. 
I have a few ideas on how to do this but am putting this out there for tips or requests. share your setup and personal hacks, I obviously want this to work for more than just my setup :)

**Comment by raelgc** [comment]
This is an awesome plan!

Just out of curiosity: in which game are you using your instruments?

**Comment by gyates100895** [comment]
fofix only right now. for the rb1 guitar i dont use any mappings, i feel it makes more sense to have fofix read controller events over mapped keys, im sure theres a logical reason but i dont feel like developing that thought further at the moment lol

**Comment by gyates100895** [comment]
did a lot of research on upstart and dbus over yesterday and last night. current plans are only with upstart.

**Comment by raelgc** [comment]
@gyates100895 I'm fine with that. Let me create a branch for it. Can I call it `15.04`?

**Comment by gyates100895** [comment]
Whatever you feel is right man. Just help me get to it to edit if its different than how I did it before lol. If I havent mentioned this before, Im new to participating and am rather ignorant for now. I know how to fix problems but not how to properly publicize them. Which would be ideal, you know, with rapid progress, adding features, fixing problems n shit lol

**Comment by gyates100895** [comment]
What would be a proper way to ask you about specific lines of code? I would like to both comment and possibly rearrange the settings that have true\false values. For example, better differentiate driver options that affect how xboxdrv presents itself to the system vs options that only affect the internal that can be passed via the options field. Really I am trying to clear up the default file while simultaneously adding hierarchical option appending in a way the user could understand. that way a user can "limit by level" where their options are applied. I know how to work the conf file but have a feeling you would have a better idea on how you want options presented. Another way to put it, I know how I want to use it but you have more experience with how the average user would view and use it

**Comment by raelgc** [comment]
@gyates100895 I think the usual fork/pull-request process is fine. Then I'll see how to handle the pull-request to get it in a branch instead of master.

What the average user wants? Just plug a gamepad and get it working, if possibel with a GUI to setup/enable-disable some options :D

**Comment by gyates100895** [comment]
lol I can only do basic python guis qnd honestly prefer this method for its versatility xP but okay thats what ill do then.

**Comment by gyates100895** [comment]
maybe while im working on this, you could talk to some people and help address this https://github.com/Grumbel/xboxdrv/issues/35 ?

**Comment by raelgc** [comment]
@gyates100895 I was just kidding about the GUI. And, the "Unix way of life" will be, first, get all the config and services files proper working, and then a GUI just editing/generating some custom config.

I.e., proper service and configs are the most important now :)

**Comment by gyates100895** [comment]
i just got a backbone example working. its on the branch "Develop-multiple-instances-1" if you want to have a look and get an idea where im going.

**Comment by raelgc** [comment]
For sure I'll take a look! Thanks for sharing @gyates100895 :)

**Comment by gyates100895** [comment]
I believe this is working, however not absolutely perfect. the added feature works like a charm with 3 controllers, 2 of which are rb instruments. occasional parent service restart required. check out my fork to see if youd like to pull it in :)

**Comment by gyates100895** [comment]
working despite timing bugs, patience and the occasional parent restart should have you set
