### ISSUE TITLE
Systemd is coming

### ISSUE THREAD

**Issue by mhalano** [raelgc/ubuntu_xboxdrv#4]
I think you create and use /etc/init.d/xboxdrv instead /etc/init/xboxdrv.conf. This change is important because Ubunu will use Systemd instead Upstart and this change probably don't affect users.

**Comment by mhalano** [comment]
Vivid will use Systemd by default, so I think we need hurry up about this issue.

**Comment by gyates100895** [comment]
Challenge accepted. Legit I will work on this. But I'm going to work on it from the perspective of my PR. Check out that and my fork, namely develop-multiple-instances-[x] to see where I'm currently at.

**Comment by gyates100895** [comment]
I anticipate having a first version by the end of the week. Spread that around for feedback and I'll keep this thread posted on where the work is. Maybe by the end of the next week a clean and stable version could be finished ;)

**Comment by gyates100895** [comment]
@raelgc I believe I correctly added you to my fork for modifications. But to pick your brain on this subject, first is there any better way to catch USB events other than udev? And second, is it within your capacity to look into a USB property characteristic to only xboxdrv's defaultly capable controllers that I could match in a udev rule? In theory this will narrow the number if times a test for either the existence if a config file, or a test of all events, will even happen. I've already rethought the "checking for config file" process immensely for systemd, which makes it much easier actually.

**Comment by gyates100895** [comment]
Just switched my work machine to systemd only. Going to tweak until it works the same as the upstart version I've posted. Is anyone opposed to using an xboxdrv configuration file as a sentinal for if a controller process should be launched? Feels like a better idea than building a file in /run to store a string that has potential to never be used by some users. Not trying to spam but at the same time, I want to build this entirely based on feedback so others simply like the implimentation.

**Comment by mhalano** [comment]
Please explian better thye part "using an xboxdrv configuration file as a
sentinal for if a controller process should be launched"

Best regards.

2015-04-21 21:07 GMT-03:00 gyates100895 <notifications@github.com>:

> using an xboxdrv configuration file as a sentinal for if a controller
> process should be launc



-- 
Marcos Alano
----------------------------------------------
P: Por que este email é tão curto?
R: http://five.sentenc.es
----------------------------------------------

**Comment by gyates100895** [comment]
Xboxdrv can use configuration files. I am proposing that the user creates a config file for each type of controller they have and place it in a directory that a service will read. Each file will be named the unique product:vendor IDs of a controller. The service will then test against these names each time a controller is connected and if the controller that was just connected has a configuration, launch a unique xboxdrv process for that controller using that unique configuration file.

**Comment by mhalano** [comment]
@gyates100895 Good idea, I guess. But I think some times the user want different configs for two equal controllers (let's say Xbox 360 Wireless Controller).

**Comment by gyates100895** [comment]
@mhalano I believe xboxdrv's config slots option could handle that. Create two configs inside the same controller config file seperated by a "next-config = true" and use the toggle button to access it on the second controller. That would work, but would be harder to use the USB of the controller to match against the event

**Comment by gyates100895** [comment]
@mhalano another idea,  have a directory /etc/xboxdrv. In there there could be a config file for xboxdrv named the vendor:product of a controller. This file would be used to start an instance of the xboxdrv daemon. The daemon would then set up controller slots for the number of that type of controller you have. For each slot, you use another config file to define it, possibly with multiple slots. Xboxdrv's --write-config option helps a lot in the construction of config files.

**Comment by mhalano** [comment]
@gyates100895 I think so. A mix is the best option. I think this changes on config system and systemd support is the top priorities. And may be can you create a PPA for Ubuntu since @raelgc already do that? I love PPAs because can keep my system clean and you can create various repositories for testing code, stable code, etc.

**Comment by gyates100895** [comment]
@mhalano I've created a repository at https://github.com/gyates100895/systemd-xboxdrv if you would like to check that out. its very rudimentary but passes the boot test, hotplug test, and properly loads configs. I'm sure there's plenty of bugs, but with some time and exposure I see it becoming much better. definitely not PPA quality yet xD

@raelgc I believe I added you as a contributer to the project, feel free to modify if it works and please give it exposure. More eyes = more fixes ;)

**Comment by mhalano** [comment]
@gyates100895 If you think is not PPA ready, the best solution is... Create a PPA! For real, you can create a repo called 'daily' or 'testing' without a good code, but with a package integrated with the system. Just a GitHub repository with a bunch of files is hard to copy to correct places to test, etc. A package permits a clean process of install->test->report bug->fix-relase fix->update system.

**Comment by melo0187** [comment]
Are there any updates about this? Is this effort still ongoing? There are 2 further issues related to this (#38 and #39)

From what I understood by this conversation and @gyates100895's fork it seems like this is becoming a much bigger deal than just making this run with systemd. Is the part with the udev-rules and the new configuration style really necessary? 
Imho the configuration method proposed in the fork is very cumbersome, but maybe I'm just getting it wrong. It sounds to me that instead of having a nice /etc/default/xboxdrv file to modify as you like you now have to get your device's USBID and create a config file with that ID and xboxdrv extension as a name and fill it with content from scratch. Is this working when using a wireless XBox Controller? 
With the old approach literally everyone was able to just install ubuntu-xboxdrv and get things started (me included, who is using the wireless version of the controller) while this method is sure to block users from using this.
I don't want to moan about your efforts, on the contrary. I am happy that someone is trying to get this working again on Ubuntu 15.04 (and all other distros that made the switch to systemd for that matter). I am just trying to provide some feedback. Having to fiddle with an rc.local file and cryptic setup was the reason for me to stop using xboxdrv on its own and instead going with ubuntu-xboxdrv, which worked flawlessly out of the box.

**Comment by raelgc** [comment]
I'll work in a simple port for systemd. Appreciate any help.

**Comment by raelgc** [comment]
Superseded by #39

**Comment by gyates100895** [comment]
@melo0187 the patch that @raelgc pulled is a lot better. Kudos to who got it done, for I have had family issues come up and their approach is much cleaner. To comment though, you are right, my approach is more round about. I was looking for a way to match entire configurations to one controller, and not just xboxdrv's slot settings. If possible, I would like to take the latest version and redevelop my multiple instances branch using this.
