### ISSUE TITLE
Bad configuration file

### ISSUE THREAD

**Issue by mhalano** [raelgc/ubuntu_xboxdrv#41]
I think the configuration file /usr/share/ubuntu-xboxdrv/uxvars is in a bad place (should be put on /etc) and with a bad name. May be you can keep the old path, /etc/default/xboxdrv.

**Comment by raelgc** [comment]
@mainmachine Can you help here?

**Comment by raelgc** [comment]
@mhalano But the `/etc/default/xboxdrv` is still present.

**Comment by mhalano** [comment]
@raelgc Oh my mistake. The pre-script uses /etc/default/xboxdrv to change
uxvars. I think is not so elegant, but "just work"
 in this way.

2015-05-21 9:05 GMT-03:00 Rael Gugelmin Cunha <notifications@github.com>:

> @mhalano <https://github.com/mhalano> But the /etc/default/xboxdrv is
> still present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raelgc/ubuntu_xboxdrv/issues/41#issuecomment-104247599>
> .
>



-- 
Marcos Alano
----------------------------------------------
P: Por que este email é tão curto?
R: http://five.sentenc.es
----------------------------------------------
