### ISSUE TITLE
Space missing in systemd service config

### ISSUE THREAD

**Issue by dlemper** [raelgc/ubuntu_xboxdrv#45]
Hi,
thanks for your work to get systemd integration for xboxdrv!
I've builded a package on my debian steam machine and just saw a bug in the systemd service configuration in lib/systemd/system/xboxdrv line 10:

    $CONTROLLER2_OPTIONS--next-controller

should be

    $CONTROLLER2_OPTIONS --next-controller

**Comment by raelgc** [comment]
Hi @dlemper, thank you for reporting this issue.

Can you, please, try to edit the file with this change? This will ask you if you want to create a Pull Request (so, say yes).

**Comment by dlemper** [comment]
Hi @raelgc,

I created the mentioned pull request and also 2 more.
The other pull requests are about XBMC keymapping. It's up to you, if you want to pull them ;-)

Thanks again for your work!

**Comment by raelgc** [comment]
Thank you @dlemper for all the PRs!
