### ISSUE TITLE
Missing space in /etc/init.d/xboxdrv

### ISSUE THREAD

**Issue by geekycow** [raelgc/ubuntu_xboxdrv#51]
Hiya

There appears to be a missing space in /etc/init.d/xboxdrv on the xboxdrv line after one of the variables.

**Comment by raelgc** [comment]
Hi @geekycow and thanks for reporting this issue.

Is this same as #45? Maybe I forgot to publish the fix in PPA.

**Comment by geekycow** [comment]
Ha, yes, so already reported.  Sorry.  Yes, same bug, so it looks like you did forget to publish the fix.  :)

**Comment by raelgc** [comment]
@geekycow I'm checking here and this fix appears to got deployed in Oct, 26 for Willy and Vivid. Can you double check it, please? https://launchpad.net/~rael-gc/+archive/ubuntu/ubuntu-xboxdrv/+packages

**Comment by geekycow** [comment]
That fits, this was on Trusty not Willy or Vivid.  Sorry.

**Comment by raelgc** [comment]
@geekycow Sorry for the delay. Fix published for Trusty! Let me know if it works!
