### ISSUE TITLE
Unable to add PPA

### ISSUE THREAD

**Issue by deepaksjcecs** [raelgc/ubuntu_xboxdrv#55]
Hi !!

I am following the instruction provided here in the README page. 
I am unable to add the PPA specified here. Is it still active yet?

deepak@deepak-VirtualBox:~/xbox/debian$ sudo apt-add-repository -y ppa:rael-gc/ubuntu-xboxdrv
Cannot add PPA: 'ppa:rael-gc/ubuntu-xboxdrv'.
Please check that the PPA name or format is correct.

I am using 14.04 Ubuntu system. Any help will be greatly appreciated.

Thanks & regards, 
Deepak

**Comment by raelgc** [comment]
Yes, it's: https://launchpad.net/~rael-gc/+archive/ubuntu/ubuntu-xboxdrv/

You'll be able to see packages for Trusty: https://launchpad.net/~rael-gc/+archive/ubuntu/ubuntu-xboxdrv/+packages.
