### ISSUE TITLE
Unable to locate package ubuntu-xboxdrv

### ISSUE THREAD

**Issue by marchandrs** [raelgc/ubuntu_xboxdrv#56]
I'm on Ubuntu 16.10 64bits.
Added the ppa and ran: sudo apt-get install ubuntu-xboxdrv

got this:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ubuntu-xboxdrv

**Comment by raelgc** [comment]
Hi @marchandrs and thank you for raising this issue.

I just build a package for Yakkety. Can you please try now?
