### ISSUE TITLE
Failed to start xboxdrv.service: Unit xboxdrv.service not found.

### ISSUE THREAD

**Issue by borgymanotoy** [raelgc/ubuntu_xboxdrv#57]
This maybe a basic error... but I do not know how I could make it work.

I get this when I run sudo apt-get install ubuntu-xboxdrv

Below is the error message I get.

borgy@windows:~$ sudo apt-get install ubuntu-xboxdrv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-rb-3.0 libdmapsharing-3.0-2 librhythmbox-core10 python-gconf python-pexpect python-ptyprocess python3-mako rhythmbox-data
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  ubuntu-xboxdrv
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 0 B/6,374 B of archives.
After this operation, 84.0 kB of additional disk space will be used.
Selecting previously unselected package ubuntu-xboxdrv.
(Reading database ... 342251 files and directories currently installed.)
Preparing to unpack .../ubuntu-xboxdrv_20151026-1_all.deb ...
Unpacking ubuntu-xboxdrv (20151026-1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu1) ...
Setting up ubuntu-xboxdrv (20151026-1) ...
Failed to start xboxdrv.service: Unit xboxdrv.service not found.
dpkg: error processing package ubuntu-xboxdrv (--configure):
 subprocess installed post-installation script returned error exit status 5
Processing triggers for bamfdaemon (0.5.3+16.10.20160929-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu4) ...
Processing triggers for dbus (1.10.10-1ubuntu1.1) ...
Errors were encountered while processing:
 ubuntu-xboxdrv
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by raelgc** [comment]
Hi @borgymanotoy and thanks for raising this issue.

Which Ubuntu version are you using? And, additionally, are you running Ubuntu directly or using any other underlying system?

**Comment by mainmachine** [comment]
Ah, I see it. In the postinst script you're trying to ```systemctl start``` before ```systemctl enable``` 

I need to sync my fork with your master before I can make a pull request, but it's an easy fix - just swap the order of those two commands.

**Comment by raelgc** [comment]
@mainmachine I just added you as a collaborator in this repo.

**Comment by mainmachine** [comment]
@raelgc - well thank you very much. :)

I must admit, I don't know how much control that gives me - can we discuss this in more detail offline?

**Comment by raelgc** [comment]
You have permission to push to the repo. But, please, let's proceed with the typical GitHub flow: clone, create a branch with name `57-fixing-service`, commit and push to `origin`, open a PR.

**Comment by mainmachine** [comment]
Ah, oops. I've already abused my power by pushing a commit. :(

Sorry! I'll do it as you suggest. I need to learn more about proper contributor etiquette.

**Comment by raelgc** [comment]
@mainmachine no problem! Thank you for the fixing! I'll publish a new Ubuntu package in the next days.

**Comment by mainmachine** [comment]
Excellent, and I'll read up on proper git collaboration practices. :D

@borgymanotoy - this should be fixed in the ppa soon!

**Comment by raelgc** [comment]
Ok, I just got some free time and published for all `systemd` releases of Ubuntu. Please @borgymanotoy, upgrade and let us know if it's working!

**Comment by spatefl** [comment]
I have version 17.10. I have a xbox one wired controller. I am trying to enable the xboxdvr.service but it says it does not exist. Im lost. PLease Help! Thank you!                                                                                             sudo apt install xboxdvr
[sudo] password for stephen: 
Sorry, try again.
[sudo] password for stephen: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xboxdvr
stephen@gizmo-xps:~$ sudo apt install xboxdvr.service
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xboxdvr.service
E: Couldn't find any package by glob 'xboxdvr.service'
E: Couldn't find any package by regex 'xboxdvr.service'
stephen@gizmo-xps:~$ sudo apt-get git clone http://pingus.seul.org/~grumbel/xboxdrv.git
E: Invalid operation git
stephen@gizmo-xps:~$ sudi systemctl enable xboxdrv.service
No command 'sudi' found, did you mean:
 Command 'sudo' from package 'sudo' (main)
 Command 'sudo' from package 'sudo-ldap' (universe)
sudi: command not found
stephen@gizmo-xps:~$ sudo systemctl enable xboxdrv.service
Failed to enable unit: Unit file xboxdrv.service does not exist.
stephen@gizmo-xps:~$ sudo apt-get install xboxdrv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xboxdrv is already the newest version (0.8.8-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
stephen@gizmo-xps:~$ sudo systemctl enable xboxdrv.service
Failed to enable unit: Unit file xboxdrv.service does not exist.
stephen@gizmo-xps:~$ ^C
stephen@gizmo-xps:~$ sudo systemctl enable xboxdrv
Failed to enable unit: Unit file xboxdrv.service does not exist.
stephen@gizmo-xps:~$ ^C
stephen@gizmo-xps:~$

**Comment by raelgc** [comment]
Hi @spatefl. The package was not published in 17.10. I just fired the package building in the PPA. In few minutes it'll be available. Sorry for the inconvenience.
