### ISSUE TITLE
Editing Default Button Mapping In Joystick Preferences Prevents Steam From Loading Properly

### ISSUE THREAD

**Issue by seecolinslash** [raelgc/ubuntu_xboxdrv#59]
I'm trying to use a wired Xbox 360 Controller "For Windows" (i.e. the PC version of the Xbox 360 controller), as it is the only Xbox 360 or Xbox One controller I've managed to get operational under Ubuntu 16.04.

Thanks to your ppa, I was able to get it working with Steam and Rocket League. However, the right thumbstick's axes were opposite what they should be in the game, so I tried editing the thumbstick in "Joystick Preferences" under "System Settings." However, when I tried to switch the default values for axes 2 and 3 to correct the right joystick orientation in Rocket League, it consistently prevented me from launching the Steam client.

If I use anything other than the default button mapping, when I try to launch Steam, first I'll briefly get the "Verifying Installation..." window, followed immediately by the "Login" window. When I attempt to login with the correct username and password, it proceeds with the "Connecting to Steam..." window and then kicks me back to the login screen again. It takes three of four attempts at logging in for Steam to load, but when it does the Steam client window doesn't open. My Steam notification pop-ups will appear in the lower right-hand corner of the screen, but the Steam client itself never appears. I can see the Steam process running in System Monitor, consuming 38 MB of memory, but it never loads the window.

When I switch the button mapping back to the defaults, Steam loads without issue. I've managed to get around this button mapping issue for now by editing the thumbstick layout within Rocket League's controller settings. However, now my Right Trigger is mapped to the Start button and there doesn't seem to be a way to edit what button the Start button is from within Rocket League itself.

Let me know if you need additional info, like terminal output. Thanks for creating this ppa!

**Edit:** I'm using the new AMD open source drivers on Ubuntu 16.04 and had to use the following terminal command to get Steam to load properly: "LD_PRELOAD='/usr/$LIB/libstdc++.so.6' DISPLAY=:0 steam"

**Comment by mainmachine** [comment]
Honestly, I would try with the xboxdrv service disabled - Valve recently updated their support for lots of different controllers in the Steam Client itself. For games launched fromSteam you may find that you don't need the xboxdrv driver running at all - in fact its' possible that having both running at the same time could cause conflicts.

Are you on the Steam Beta Client, or the mainstream one?

You can temporarily stop the xboxdrv service like this to test:

```sudo systemctl stop xboxdrv```

This just stops it in the running session, it will start again on reboot or with a manual "start" command, but if this resolves the issue for you, then you can run this to disable the service on boot without uninstalling the driver entirely:

```sudo systemctl disable xboxdrv```

Let us know if helps or not!

**Comment by seecolinslash** [comment]
Thanks for the response!

I'm using the Steam's stable channel at the moment. I installed xboxdrv
because Steam wouldn't recognize my controllers at all.

However, since updating Mesa to version 12.0.6 yesterday the button mapping
issues have disappeared entirely and everything is working flawlessly.

I'll keep your advice in mind should the problem crop up again, but for now
I won't try to fix what is no longer broken.

Thanks!

On Feb 15, 2017 3:03 PM, "David Martinka" <notifications@github.com> wrote:

Honestly, I would try with the xboxdrv service disabled - Valve recently
updated their support for lots of different controllers in the Steam Client
itself. For games launched fromSteam you may find that you don't need the
xboxdrv driver running at all - in fact its' possible that having both
running at the same time could cause conflicts.

Are you on the Steam Beta Client, or the mainstream one?

You can temporarily stop the xboxdrv service like this to test:

sudo systemctl stop xboxdrv

This just stops it in the running session, it will start again on reboot or
with a manual "start" command, but if this resolves the issue for you, then
you can run this to disable the service on boot without uninstalling the
driver entirely:

sudo systemctl disable xboxdrv

Let us know if helps or not!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/raelgc/ubuntu_xboxdrv/issues/59#issuecomment-280138069>,
or mute the thread

**Comment by mainmachine** [comment]
Awesome, glad it's working now, although I'm not sure how a Mesa update would do it. :)
