### ISSUE TITLE
Edit launch options

### ISSUE THREAD

**Issue by pablopenna** [raelgc/ubuntu_xboxdrv#60]
Is there any way I can change the launch options which are used when initializing the driver on startup?

**Comment by pablopenna** [comment]
the default ones are
`/usr/bin/xboxdrv --daemon --silent --pid-file /var/run/xboxdrv.pid --dbus disabled --mimic-xpad --mimic-xpad-wireless --detach-kernel-driver --next-controller --mimic-xpad --mimic-xpad-wireless --detach-kernel-driver --next-controller --mimic-xpad --mimic-xpad-wireless --detach-kernel-driver --next-controller --mimic-xpad --mimic-xpad-wireless --detach-kernel-driver`

**Comment by raelgc** [comment]
Hi @pablopenna. Yes, you can edit `/etc/default/xboxdrv`.

**Comment by pablopenna** [comment]
Thank you very much
