### ISSUE TITLE
Does not work on Ubuntu disco 64bit

### ISSUE THREAD

**Issue by domeniko-gentner** [raelgc/ubuntu_xboxdrv#70]
```
Err:6 http://ppa.launchpad.net/rael-gc/ubuntu-xboxdrv/ubuntu disco Release                                       
  404  Not Found [IP: 91.189.95.83 80]
```
I have tried different approaches, also adding other repositories, apt cannot find the correct package. I have installed it manually, but would be nice if it could work out of the box.
edit: Manual installation didn't work, Ubuntu is rolling it back, no idea why.

**Comment by raelgc** [comment]
Hi @scorcher24 and sorry for the inconvenience. I'm just fired a build for Disco and it's now available to install. Do you mind to try install again?

**Comment by domeniko-gentner** [comment]
Installs now. Thanks a lot :)
