### ISSUE TITLE
Uninstall should un-blacklist xpad

### ISSUE THREAD

**Issue by darkporpoise** [raelgc/ubuntu_xboxdrv#72]
As I understand it, during install, `/etc/modprobe.d/xboxdrv.conf` is created in order to blacklist `xpad` kernel module to avoid conflicts.

When uninstalling, that file should really get removed so that the user still has a working driver. I understand that they can `sudo apt-get purge ubuntu-xboxdrv` to resolve the issue but that seems overkill and not obvious.

This has taken hours for me to track down on Ubuntu 20.04.

**Comment by mainmachine** [comment]
@darkporpoise it has been quite a while, but this should be fixed simply with #74 which I have not tested but we're talking a VERY simple change here
