### ISSUE TITLE
ubuntu impish Release' does not have a Release file.

### ISSUE THREAD

**Issue by ftzi** [raelgc/ubuntu_xboxdrv#73]
E: The repository 'http://ppa.launchpad.net/rael-gc/ubuntu-xboxdrv/ubuntu impish Release' does not have a Release file.

**Comment by raelgc** [comment]
Hi @SrBrahma and thanks for raising this issue. Really sorry, I just published for the missing releases.

**Comment by ftzi** [comment]
Thanks!
