### ISSUE TITLE
"The repository 'https://ppa.launchpadcontent.net/grumbel/ppa/ubuntu jammy Release' does not have a Release file."

### ISSUE THREAD

**Issue by cupofdirtfordinner** [raelgc/ubuntu_xboxdrv#75]
Whenever I try to do the first step in the installation, I am greeted with this message. I am on ubuntu 22.04 (jammy jellyfish)

**Comment by raelgc** [comment]
This repository is not for `grumbel` PPA. My PPA is `ppa:rael-gc/ubuntu-xboxdrv` and it has a `jammy` release.
